version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/joshdk/posh
    steps:
      - checkout
      - run: ./godelw version
      - run: ./godelw verify --apply=false
